# Generated by Django 5.2.1 on 2025-05-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='infractions/'),
        ),
    ]
