# Generated by Django 5.2 on 2025-06-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infractions', '0002_infraction_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('latitud_uno', models.FloatField()),
                ('longitud_uno', models.FloatField()),
                ('latitud_dos', models.FloatField()),
                ('longitud_dos', models.FloatField()),
                ('espacio_disponible', models.IntegerField()),
            ],
        ),
    ]
