# Generated by Django 5.2 on 2025-06-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0002_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='año',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='placa',
            field=models.CharField(default='SIN_PLACA', max_length=20),
        ),
    ]
