# Generated by Django 5.2 on 2025-06-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0004_infraccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraccion',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
