# Generated by Django 5.2 on 2025-04-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaRestringida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenada1_lat', models.FloatField()),
                ('coordenada1_lon', models.FloatField()),
                ('coordenada2_lat', models.FloatField()),
                ('coordenada2_lon', models.FloatField()),
            ],
        ),
    ]
